# Generated by Django 4.2.6 on 2023-11-01 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseEducation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Название"),
                ),
                (
                    "speciality",
                    models.CharField(
                        max_length=150, verbose_name="Специальность"
                    ),
                ),
                (
                    "period",
                    models.CharField(max_length=150, verbose_name="Период"),
                ),
            ],
            options={
                "verbose_name": "Дополнительное образование",
                "verbose_name_plural": "Дополнительные образования",
            },
        ),
        migrations.CreateModel(
            name="HigherEducation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Название"),
                ),
                (
                    "speciality",
                    models.CharField(
                        max_length=150, verbose_name="Специальность"
                    ),
                ),
                (
                    "period",
                    models.CharField(max_length=150, verbose_name="Период"),
                ),
            ],
            options={
                "verbose_name": "Высшее образование",
                "verbose_name_plural": "Высшие образования",
            },
        ),
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=150, verbose_name="Заголовок"),
                ),
                (
                    "photo",
                    models.ImageField(
                        default=None, upload_to="photo/", verbose_name="Фото"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Муж."), ("Female", "Жен.")],
                        verbose_name="Пол",
                    ),
                ),
                (
                    "grade",
                    models.CharField(max_length=150, verbose_name="Уровень"),
                ),
                (
                    "birthday",
                    models.DateField(
                        blank=True, null=True, verbose_name="День рождения"
                    ),
                ),
                (
                    "telegram",
                    models.CharField(max_length=50, verbose_name="Телеграм"),
                ),
                (
                    "github",
                    models.CharField(max_length=50, verbose_name="GitHub"),
                ),
                (
                    "portfolio",
                    models.CharField(max_length=50, verbose_name="Портфолио"),
                ),
                ("about_me", models.TextField(verbose_name="О себе")),
                (
                    "type_work",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Любой"),
                            (1, "Оффис"),
                            (2, "Гибрид"),
                            (3, "Удаленная"),
                        ],
                        default=0,
                        verbose_name="Тип работы",
                    ),
                ),
                (
                    "status_finded",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Не в поиске"),
                            (1, "В поиске"),
                            (3, "Найдена"),
                        ],
                        default=0,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Создание резюме"
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кандидат",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.city",
                        verbose_name="Город",
                    ),
                ),
            ],
            options={
                "verbose_name": "Резюме",
                "verbose_name_plural": "Резюме",
                "ordering": ["candidate"],
                "default_related_name": "resumes",
            },
        ),
        migrations.CreateModel(
            name="SkillInResume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_list",
                        to="resume.resume",
                        verbose_name="Резюме",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.skill",
                        verbose_name="Скилл",
                    ),
                ),
            ],
            options={
                "verbose_name": "Скилл в резюме",
                "verbose_name_plural": "Скиллы в резюме",
                "ordering": ("resume",),
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.CharField(max_length=150, verbose_name="Должность"),
                ),
                ("period", models.DurationField(verbose_name="Период")),
                ("duties", models.TextField(verbose_name="Обязанности")),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiences",
                        to="resume.resume",
                        verbose_name="Опыт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Опыт",
                "verbose_name_plural": "Опыт",
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="educations",
                        to="resume.courseeducation",
                    ),
                ),
                (
                    "higher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="educations",
                        to="resume.highereducation",
                    ),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="educations",
                        to="resume.resume",
                        verbose_name="Образование",
                    ),
                ),
            ],
            options={
                "verbose_name": "Образование",
                "verbose_name_plural": "Образования",
            },
        ),
        migrations.AddConstraint(
            model_name="skillinresume",
            constraint=models.UniqueConstraint(
                fields=("skill", "resume"), name="unique_skill_resume"
            ),
        ),
    ]
